exp_name: covid19_lianxiangjia
model_state_dict_dir: ./wandb
run_ids:
 - qym2syx7
 - 1hwoawtv
 - 21j5scsr
 - 2vd380bi
 - 2e4j9h08

last_k_model: 1

data_home: ../data4bert
test_data: "*test*.json"
meta: meta.json
 
device_num: 0

# encoder
encoder: BERT
bert_path: /data/yubowen/experiments/pretrained_model/bert-base-cased

# parameters
shaking_type: cln
batch_size: 8
force_split: true
max_test_seq_len: 512
sliding_len: 50
visual_field: -1 # -1: use recommended value
correct: whole_text # head_n_tail, only_head, whole_text

# results
save_res: true
save_res_dir: ../results
# score: set true only when test set tagged
score: false
