res_dir: ../results/covid19_lianxiangjia
run_ids:
 - qym2syx7
 - 1hwoawtv
 - 21j5scsr
 - 2vd380bi
 - 2e4j9h08
 
last_k_res: 1

keyword: test_data

vote_threshold: 3

ensemble_res_dir: ../results/covid19_lianxiangjia/ensemble