experiment_name: covid19_lianxiangjia
run_name: group3

data_home: &data_home ../data4bert

train_data: train_data_3.json
valid_data: valid_data_3.json
meta: meta.json
 
device_num: 1

wandb: false
path_to_save_model: ../model_state

encoder: BERT
bert_path: /home/wangyucheng/opt/transformers_models_h5/bert-base-cased

hyper_parameters:
 batch_size: 20
 epochs: 200
 lr: 5e-5
 seed: 2333
 log_interval: 10
 max_seq_len: 128
 pred_max_seq_len: 128
 sliding_len: 50
 visual_field: -1 # -1: use recommended value
 shaking_type: cln
 
 # CosineAnnealingWarmRestarts
 scheduler: CAWR # Step
 T_mult: 1
 rewarm_epoch_num: 2
 
#  # StepLR
#  scheduler: Step
#  decay_rate: 0.99
#  decay_steps: 100
 
# when to save the model state dict
f1_2_save: 0
# whether train from scratch
fr_scratch: true
# note 
note: start from scratch
# if not fr scratch, set a model_state_dict
model_state_dict_path: stake